#----------------------------------------------------------------------
# This file was generated by img2py.py
#
# python img2py.py  -i  flag-green.png greenflagIcon.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

flag_green = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAABC9J"
    "REFUOI2lld1vlEUUxp8zc2be9113tx9QGgWtgFAsUTSkUUJCDRd+f1wQE6+4UsOdXKjXJkaC"
    "if+BNyZGxRsDRiGSQIwxSBAqETC1dCnUbVmh3W7pLt33Y+Z4sdsCkUTAkzxXk/nNM+d9nzO0"
    "bt06RUQ+TdPBwcHBn4eHh7cYY4ZFRDUaDd+7tgMnfzyLuy0WESEiENGVSqXyZ5w2q2NjZWx+"
    "dzX1vphHbfwatry5AVZrxKnD8Z0jdwSm9evXo6OjAwA6S6XS0Wq1+hKAywBo19/bZfJETVmj"
    "KbIsUaAlDBhRwBIGjFzACC3fHjw0NETFfFE8+dVTk1Pn4/7ZkVXP93wR2/hQrTZ/LpY4Lebz"
    "YKVxqXIN377zOpoSY6XNo4g8vrxyGon3gABEBAKw+/79oG3btlEx3yGi/OqJixMj8eOztveZ"
    "TiAvYlhdiAL+NbT6VBTwuTDgS6Hl6cDoOhHir74/654dWoONfT1grboApADqAMAEAhEgBBAR"
    "xVmCVNLsPmPZsl5rWK01rN5grcBaCbOat1bPR5Ybu3c+tWBYRRBYAAcAfLwElpv6IgC0JoSW"
    "OQoYhrUERvvAaliryRqtLKsiK1W0VsFoBQjKAnkfgq+bifNhoNF23G52W0YrhFYjDBhGK7JG"
    "68BoBEbDsoI1GoUOC8SSZbH/8LW+/o8eQZf7fOF3SCaYbcQtsPMezjkIhLz3YFYIA0ZkGawV"
    "rFEw3ALnCxYWypeOVfHbycs+3x/uGO2ffbGnMzexrCM8qhV9Y1hdcd6DszRFkiQQLXDOIWCF"
    "0LKEAQsrkjBk5HIG2pOaKS3QhZF5dTVuoPBkzq5YllvOSh1UhANEOJE5f7WnK0J1rglOsxRJ"
    "kgIsyDKHvFaIrKYoZDJKwSce5YtzmCrXUXe+xt3qbHd3eLRgzMFOBKdsg7LJ+jz+mprHZ9uP"
    "3UhemmZIdALyAucyWKsRhaYZBTxcvdA4c/74dGW62RwPB8LRVVvzo/s3jc3guTw2be3C9Q0Z"
    "Huwt6Ac6C7K8M/KflF/FEyuXYWR6DjQwMEBhEAlI1szMzIx2Pe3ee3vf1n17+w5Xfiq9Jd9l"
    "JYyPVzE8fhXeC5KKply3qEJopbsYevGChcQhTjM82rcCezYeWoo0BUEgIrKmVquNlMvlzaTp"
    "zKYdq/Qrezfi9P5JTFSuIT+Qk2gFi1toijIEqFaUj7z8x+2HUJqmUEpBpPXxtCXlEsHYkWn5"
    "9IXjftcPW/DYdYc9A4fvaPgsgbMsA1Hrb3bOwSXiAWChlkhzLsUHDx+6K+AtjttFWZbdsigi"
    "/9pwV44XAc65xSBCRJZuck9g59wSyHsPtJINESHv/T1b5nq9vuQsyzJBaxZB/k8fcGuPiwAM"
    "gIfQekEKi4e0y98k9x/y+qaNGsAvbagCEAEIAdi2uC3dXle4MRQXa+nG/wAkB+eGnJ9P7QAA"
    "AABJRU5ErkJggg==")
getflag_greenData = flag_green.GetData
getflag_greenImage = flag_green.GetImage
getflag_greenBitmap = flag_green.GetBitmap
getflag_greenIcon = flag_green.GetIcon

