#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

flag_red = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAA95J"
    "REFUOI2dlc1rXFUYxn/n3HvnI5kvm6RgwdhQWmoXXQgp2k033agIlW5cCFYQceVK/AcSKy5V"
    "cCHislUUoZsKUkLRQqm2U7BN7HSaWjsmk0nSMNP5yNw5H6+LTJIJLmr6wHvhcjjPec7zvs+9"
    "6uDBg1op5Y0xk5OTk1eKxeLLURgWBXS71fLx4iLL3rNbhCIiSimUUstLS0uluNtdu7d/P6fm"
    "5tTrzSa9kRGWrKW9dy+pUonp/0msDh06RD6fByjMz8/PrK2tvQZUAbVw5oz8cu2a9sYo8V68"
    "MWI7Hbr1ujSdowGsA89ns+zJ54kbDfAepTXqxIkTKlcoiDg3sbCwUObWrdILYXhuj9Y/jVl7"
    "aywIzApgRLja7XJJ5MlqlSIUQEQQ77HWuiQcEZgOYSozPHx/eGjo94zWN0RkdqLd/vsLpVbv"
    "Qes8xCsjI+6b1VVeAq6Pjz8T1+sG71tfZ7OEauCUjQcAVmkdhun0gUQ+fyDKZN6MhocJ02kJ"
    "0+nmkaGh5hupVDuRza4np6bSq7VaIspmLzQqlU870MppvaGYvurBpiqt0VEkQRT5MJUiymRU"
    "olDQiVwul8jnc0OjoxAEtCqVfxrl8kffzs19dwH850BybGynYsVOKFAoFWy+S78xAVCbnbW1"
    "YnHqrZs3Pwbce8D7wFA+j+92CZ33OOfAOeUHVIsI3nu8c3jnEBECETorK/7Bw4e0Ewk/fuzY"
    "6V+PH3+1Xa0+XL5+faazuPhjp9FYTiaThNYYer0eOIezdpu3P17KWrS1xI2GXq3Xlc1m9ei+"
    "fUxkMgnp9Ua79fpF02xeEOd+89auzAJH45jQGIMxBpzDOrftgohycczjZpP2+jqSTpMvFOqj"
    "xtwO7tyZKd+/f/FctXpjFexxIAQ+G2ySsXZb8TZxDBRrvd4fc73eUiGd/uuoyN2xSuXuK9PT"
    "j7rlMqkrVzgDFM+eDRYvX5ZHt2/7L6tVfgBOQ9+KOAYRnLW6IfLhHq3Pf+9c9e1sVoJ2G4ki"
    "Jk6eJEyl+DOdVpWFBb12+LA8KJX8GLhUFPFsMskHQAmYAUJrLabXQ0Rwzvmycz/f63QWX0wm"
    "g7E4phNFaO+Zv3RJEvW6XG00RIF7rn/9dwGM2agdVhiD1nqTGA3aA3eck0/i2J8KAqwxvFOr"
    "sRuE1tqtwDnn8OABuiISe89Xvd6uCHco7kPZ7XED/pPG3SveJHDObYVPRAY+HU9BvDlim0mD"
    "jWSLiPLeP7XksNVqbSmz1gogfeKn94GdHueACBhn4w+S3TykDz9Q7gnlg4GNAXC1T6qBNJAC"
    "Ev0K+xX01zUbtg02YuvG/wIRNEX6jHrsmwAAAABJRU5ErkJggg==")
getflag_redData = flag_red.GetData
getflag_redImage = flag_red.GetImage
getflag_redBitmap = flag_red.GetBitmap
getflag_redIcon = flag_red.GetIcon

